AWSTemplateFormatVersion: '2010-09-09'

# Description of what this change includes:
# Corrected validation errors including format version, resource type syntax,
# section headers, indentation, and placement of BucketPolicy. Ensures proper
# structure and compatibility for deploying an S3 bucket with website hosting
# and public access policy.

# Revision number: 1.1
# Date: 2025-12-02

Description: S3 bucket with website hosting and public read policy

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join 
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Bucket
                - "/*"
      Bucket: !Ref S3Bucket

Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
    Description: URL for website hosted on S3

  S3BucketSecureURL:
    Value: !Join 
      - ""
      - - "https://"
        - !GetAtt S3Bucket.DomainName
    Description: Name of S3 bucket to hold website content
